/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.FornecedorController;
import br.ulbra.model.Cliente;
import br.ulbra.model.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class FornecedorView extends javax.swing.JFrame {

    /**
     * Creates new form FornecedorView
     */
    public FornecedorView() {
        initComponents();
        controller = new FornecedorController();
        this.setLocationRelativeTo(null);
        initTableModel();
        atualizarTabela();

    }

    private void limparCampos() {
        txtIdFor.setText("");
        txtNomeRazaoFor.setText("");
        txtNomeFanFor.setText("");
        txtTelefoneFor.setText("");
        txtEmailFor.setText("");
        DefaultTableModel model = (DefaultTableModel) tblFornecedor.getModel();
        model.setRowCount(0);  // apaga todas as linhas;
    }

    private FornecedorController controller;

    private void atualizarTabela() {
        try {
            DefaultTableModel modelTbl = (DefaultTableModel) tblFornecedor.getModel();
            modelTbl.setRowCount(0);
            List<Fornecedor> lista = controller.listar();
            for (Fornecedor u : lista) {
                modelTbl.addRow(new Object[]{u.getIdFor(), u.getNomeRazao(), u.getNomeFantasia(), u.getTelefone(), u.getEmail()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erro ao listar:" + ex.getMessage());
        }
    }

    private void initTableModel() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"ID","Nome Razão", "Nome Fantasia", "telefone", "E-mail"}) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblFornecedor.setModel(model);
    }

    public void setBotoes(int op) {
        switch (op) {
            case 1:
                btnSalvarFor.setEnabled(false);
                btnExcluirFor.setEnabled(true);
                btnEditarFor.setEnabled(true);
                break;
            default:
                btnSalvarFor.setEnabled(true);
                btnExcluirFor.setEnabled(false);
                btnEditarFor.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        txtIdFor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFanFor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeRazaoFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefoneFor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFor = new javax.swing.JTextField();
        btnSalvarFor = new javax.swing.JButton();
        btnLimparFor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        btnEditarFor = new javax.swing.JButton();
        btnExcluirFor = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        txtIdFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdForActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome (Razão): ");

        txtNomeFanFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFanForActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome (Fantasia):");

        txtNomeRazaoFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRazaoForActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone: ");

        jLabel5.setText("E-mail:");

        txtEmailFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailForActionPerformed(evt);
            }
        });

        btnSalvarFor.setText("SALVAR");
        btnSalvarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarForActionPerformed(evt);
            }
        });

        btnLimparFor.setText("LIMPAR");
        btnLimparFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparForActionPerformed(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Razão", "Nome Fantasia", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedor);

        btnEditarFor.setText("EDITAR");
        btnEditarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarForActionPerformed(evt);
            }
        });

        btnExcluirFor.setText("EXCLUIR");
        btnExcluirFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirForActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel6.setText("FORNECEDOR");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno.saolucas\\Downloads\\Fornecedor.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarFor)
                        .addGap(48, 48, 48)
                        .addComponent(btnLimparFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtIdFor)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeFanFor)
                            .addComponent(txtNomeRazaoFor)
                            .addComponent(txtTelefoneFor)
                            .addComponent(txtEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnEditarFor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirFor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeRazaoFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFanFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarFor)
                    .addComponent(btnExcluirFor)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarFor)
                    .addComponent(btnLimparFor))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdForActionPerformed

    private void txtNomeFanForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFanForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFanForActionPerformed

    private void txtNomeRazaoForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRazaoForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRazaoForActionPerformed

    private void txtEmailForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailForActionPerformed

    private void btnSalvarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarForActionPerformed
        try {
            String nomeRazao = txtNomeRazaoFor.getText().trim();
            String nomeFantasia = txtNomeFanFor.getText().trim();
            String telefone = txtTelefoneFor.getText().trim();
            String email = txtEmailFor.getText().trim();
            if (nomeRazao.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nome é obrigatório");
                return;
            }
            Fornecedor f = new Fornecedor(0, nomeRazao, nomeFantasia, telefone, email);
            controller.salvar(f);
            javax.swing.JOptionPane.showMessageDialog(this, "Fornecedor salvo (ID=" + f.getIdFor() + ")");
            atualizarTabela();
            limparCampos();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnSalvarForActionPerformed

    private void btnLimparForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparForActionPerformed
        txtIdFor.setText(null);
        txtNomeRazaoFor.setText(null);
        txtNomeFanFor.setText(null);
        txtEmailFor.setText(null);
        txtTelefoneFor.setText(null);     }//GEN-LAST:event_btnLimparForActionPerformed

    private void btnEditarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarForActionPerformed
        try {
            int id = Integer.parseInt(txtIdFor.getText());
            String nomeRazao = txtNomeRazaoFor.getText().trim();
            String nomeFantasia = txtNomeFanFor.getText().trim();
            String email = txtEmailFor.getText().trim();
            String tel = txtTelefoneFor.getText().trim();
            Fornecedor f = new Fornecedor(id, nomeRazao, nomeFantasia, email, tel);
            controller.atualizar(f);
            javax.swing.JOptionPane.showMessageDialog(this, "Atualizado com sucesso");
            atualizarTabela();
            limparCampos();
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente para atualizar");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + ex.getMessage());
        }    }//GEN-LAST:event_btnEditarForActionPerformed

    private void btnExcluirForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirForActionPerformed
        try {
            int id = Integer.parseInt(txtIdFor.getText());
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Remover cliente ID " + id + "?", "Confirma", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }
            controller.excluir(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Removido");
            atualizarTabela();
            limparCampos();
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente para remover");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao remover: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirForActionPerformed

    private void tblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedorMouseClicked
        int linha = tblFornecedor.getSelectedRow();
        if (linha != -1) {
            txtIdFor.setText(tblFornecedor.getValueAt(linha, 0).toString());
            txtNomeRazaoFor.setText(tblFornecedor.getValueAt(linha, 1).toString());
            txtNomeFanFor.setText(tblFornecedor.getValueAt(linha, 2).toString());
            txtTelefoneFor.setText(tblFornecedor.getValueAt(linha, 3).toString());
            txtEmailFor.setText(tblFornecedor.getValueAt(linha, 4).toString());
        }

    }//GEN-LAST:event_tblFornecedorMouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        atualizarTabela();
        setBotoes(0);
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarFor;
    private javax.swing.JButton btnExcluirFor;
    private javax.swing.JButton btnLimparFor;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvarFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtEmailFor;
    private javax.swing.JTextField txtIdFor;
    private javax.swing.JTextField txtNomeFanFor;
    private javax.swing.JTextField txtNomeRazaoFor;
    private javax.swing.JTextField txtTelefoneFor;
    // End of variables declaration//GEN-END:variables
}
